import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Award from "@/components/award";
import Cta from "@/components/cta";
import Establish from "@/components/establish";
import Footer from "@/components/footer";
import Join from "@/components/join";
import Pottery from "@/components/pottery";
import Tabs from "@/components/tabs";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Teachable Online Course Platform: Create & Sell Courses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <Pottery />
      <Join />
      <Tabs />
      <Establish />
      <Award />
      <Cta />
      <Footer />
    </>
  );
}
